try {
} catch (e) {
    let n = 1;
}
